disabled_rules:
  - todo
  - trailing_comma
  - opening_brace
  - force_try

included:
  - Sources/
  - Tests/

identifier_name:
  excluded:
    - h1
    - h2
    - h3
    - p1
    - p2
    - r
    - vm
    - B
    - KB
    - MB
    - GB
    - id
    - ip

type_name:
  excluded:
    - T
    - VM