on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: "/Applications/Xcode_15.4.app/Contents/Developer"

# Limit GITHUB_TOKEN permissions to read-only for repo contents
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./Scripts/brew.sh
    - name: Run lint
      run: make lint

  build:
    name: Build
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Run build
      run: make build

  test:
    name: Test
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Run tests
      run: make test
