on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEVELOPER_DIR: "/Applications/Xcode_14.3.1.app/Contents/Developer"

# Limit GITHUB_TOKEN permissions to read-only for repo contents
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: ./Scripts/brew.sh
    - name: lint
      run: make lint

  build:
    name: Build
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make build
